import json
import glob

cells_to_append = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. 개체 생애 (Lifecycle) 요약\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import config.interp_config as cfg\n",
            "BEST_N = 1\n",
            "ALARM_WINDOW = 14\n",
            "\n",
            "def print_lifecycle(serial_num, disk_info):\n",
            "    df_entity = df_test[df_test['base_serial'] == serial_num].sort_values(fe_cfg.DATE_COL)\n",
            "    first_obs = df_entity[fe_cfg.DATE_COL].min().date()\n",
            "    last_obs = df_entity[fe_cfg.DATE_COL].max().date()\n",
            "    \n",
            "    print(f\"\\n  [개체 생애 (Lifecycle) 요약: {serial_num}]\")\n",
            "    print(f\"  - 데이터 수집 기간 : {first_obs} ~ {last_obs} (총 {len(df_entity)}일간 관측)\")\n",
            "    \n",
            "    raw_alarms = df_entity[df_entity['_prob'] >= BEST_T]\n",
            "    \n",
            "    if disk_info['is_alarmed'] == 1:\n",
            "        if disk_info['is_failed'] == 1:\n",
            "            first_alarm = last_obs - pd.Timedelta(days=disk_info['lead_time']) if not np.isnan(disk_info['lead_time']) else \"해당 없음\"\n",
            "            print(f\"  - 시스템 최종 확정 : {first_alarm} (고장 {disk_info['lead_time']}일 전 감지)\")\n",
            "        else:\n",
            "            alarms = (df_entity['_prob'] >= BEST_T).astype(int)\n",
            "            rolling = alarms.rolling(window=ALARM_WINDOW, min_periods=1).sum()\n",
            "            idx = np.where(rolling >= BEST_N)[0]\n",
            "            first_alarm_date = df_entity[fe_cfg.DATE_COL].iloc[idx[0]].date() if len(idx) > 0 else \"N/A\"\n",
            "            days_before = (last_obs - first_alarm_date).days if len(idx) > 0 else \"N/A\"\n",
            "            print(f\"  - 시스템 최종 확정 : {first_alarm_date} (알람 발령 후 {days_before}일 동안 고장 없이 정상 동작함)\")\n",
            "    else:\n",
            "        print(f\"  - 시스템 최종 확정 : 없음 (경보 미발령)\")\n",
            "        \n",
            "    if len(raw_alarms) > 0:\n",
            "        alarm_details = []\n",
            "        for d in raw_alarms[fe_cfg.DATE_COL].dt.date.values:\n",
            "            days_before = (last_obs - d).days\n",
            "            alarm_details.append(f\"D-{days_before}\")\n",
            "        print(f\"  - 모델 단일 경고 이력: 총 {len(raw_alarms)}회 ({', '.join(alarm_details)})\")\n",
            "    else:\n",
            "        print(f\"  - 모델 단일 경고 이력: 없음\")\n",
            "        \n",
            "    if disk_info['is_failed'] == 1:\n",
            "        status = '✅ 탐지 성공 (Hit)' if disk_info['is_alarmed'] else '❌ 미탐 (Miss)'\n",
            "        fail_text = '고장'\n",
            "    else:\n",
            "        status = '❌ 오탐 (False Alarm)' if disk_info['is_alarmed'] else '✅ 정상 정탐 (True Negative)'\n",
            "        fail_text = '정상'\n",
            "        \n",
            "    print(f\"  - 최종 평가 결과   : {status} ({fail_text} 디스크)\\n\")\n",
            "\n",
            "for serial in target_serials:\n",
            "    info = df_best_disk[df_best_disk['base_serial'] == serial].iloc[0]\n",
            "    print(\"=\"*60)\n",
            "    print_lifecycle(serial, info)\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Waterfall Plot (최대 위험 시점 피처 기여도)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import shap\n",
            "for serial in target_serials:\n",
            "    df_entity = df_test[df_test['base_serial'] == serial].sort_values(fe_cfg.DATE_COL)\n",
            "    X_entity = df_entity[FEATURE_COLS].reset_index(drop=True)\n",
            "\n",
            "    # 앙상블 전체의 SHAP 평균 계산\n",
            "    sv_entity_list = []\n",
            "    for model in models:\n",
            "        exp = shap.TreeExplainer(model)\n",
            "        sv_e = exp.shap_values(X_entity)\n",
            "        if isinstance(sv_e, list):\n",
            "            sv_e = sv_e[1]\n",
            "        sv_entity_list.append(sv_e)\n",
            "    mean_sv_entity = np.mean(sv_entity_list, axis=0)\n",
            "\n",
            "    # 고장 확률이 가장 높은 시점 선택\n",
            "    peak_idx = df_entity[\"_prob\"].values.argmax()\n",
            "    peak_date = df_entity[fe_cfg.DATE_COL].iloc[peak_idx].date()\n",
            "    peak_prob = df_entity[\"_prob\"].iloc[peak_idx]\n",
            "    \n",
            "    print(f\"\\n\" + \"=\"*70)\n",
            "    print(f\"[§9.2] Waterfall Plot — 개체: {serial}\")\n",
            "    print(f\"       최고 위험 시점: {peak_date} (예측 확률={peak_prob:.4f})\")\n",
            "    print(\"=\"*70)\n",
            "\n",
            "    # 첫 번째 모델 기준 expected_value 사용\n",
            "    base_vals = np.mean([shap.TreeExplainer(m).expected_value for m in models])\n",
            "    if isinstance(base_vals, np.ndarray):\n",
            "        base_vals = base_vals[1]\n",
            "\n",
            "    # data=None으로 설정하여 좌측의 연한 회색 원본 피처값을 숨김\n",
            "    explanation = shap.Explanation(\n",
            "        values=mean_sv_entity[peak_idx],\n",
            "        base_values=float(base_vals),\n",
            "        feature_names=FEATURE_COLS,\n",
            "    )\n",
            "\n",
            "    shap.plots.waterfall(explanation, max_display=15, show=False)\n",
            "    \n",
            "    # 마이너스 기호 깨짐 해결\n",
            "    fig = plt.gcf()\n",
            "    for ax in fig.axes:\n",
            "        for t in ax.texts:\n",
            "            t.set_text(t.get_text().replace('\\u2212', '-'))\n",
            "        labels = [l.get_text().replace('\\u2212', '-') for l in ax.get_xticklabels()]\n",
            "        ax.set_xticklabels(labels)\n",
            "        labels = [l.get_text().replace('\\u2212', '-') for l in ax.get_yticklabels()]\n",
            "        ax.set_yticklabels(labels)\n",
            "        \n",
            "    fig.suptitle(f\"최대 고장 위험 시점의 피처별 SHAP 기여도 분석 (대상 개체: {serial})\", fontsize=14, fontweight=\"bold\", y=1.05)\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. 시간 기반 SHAP Trajectory (고장 전 N일)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "window_days = cfg.TEMPORAL_WINDOW_DAYS\n",
            "top_n = cfg.TEMPORAL_TOP_N_FEATS\n",
            "\n",
            "for serial in target_serials:\n",
            "    df_entity = df_test[df_test['base_serial'] == serial].sort_values(fe_cfg.DATE_COL)\n",
            "    info = df_best_disk[df_best_disk['base_serial'] == serial].iloc[0]\n",
            "    \n",
            "    is_failed = info['is_failed']\n",
            "    is_alarmed = info['is_alarmed']\n",
            "    \n",
            "    alarms = (df_entity['_prob'] >= BEST_T).astype(int)\n",
            "    rolling = alarms.rolling(window=ALARM_WINDOW, min_periods=1).sum()\n",
            "    idx = np.where(rolling >= BEST_N)[0]\n",
            "    first_alarm_date = df_entity[fe_cfg.DATE_COL].iloc[idx[0]] if len(idx) > 0 else None\n",
            "    \n",
            "    if is_failed == 1:\n",
            "        ref_date = df_entity[fe_cfg.DATE_COL].max()\n",
            "        title_suffix = \"Failure Date (D-0)\"\n",
            "    else:\n",
            "        if is_alarmed == 1:\n",
            "            if first_alarm_date is not None:\n",
            "                ref_date = min(first_alarm_date + pd.Timedelta(days=5), df_entity[fe_cfg.DATE_COL].max())\n",
            "            else:\n",
            "                ref_date = df_entity[fe_cfg.DATE_COL].max()\n",
            "            title_suffix = \"Observation End (D-0)\"\n",
            "        else:\n",
            "            ref_date = df_entity[fe_cfg.DATE_COL].max()\n",
            "            title_suffix = \"Observation End (D-0)\"\n",
            "\n",
            "    start_date = ref_date - pd.Timedelta(days=window_days - 1)\n",
            "    df_window = df_entity[(df_entity[fe_cfg.DATE_COL] >= start_date) & (df_entity[fe_cfg.DATE_COL] <= ref_date)].copy().reset_index(drop=True)\n",
            "    \n",
            "    print(f\"\\n\\n\" + \"=\"*70)\n",
            "    print(f\"[§9.3] 시간 기반 SHAP Trajectory — 개체: {serial}\")\n",
            "    print(f\"       분석 기간: {start_date.date()} ~ {ref_date.date()} ({len(df_window)}일)\")\n",
            "    print(\"=\"*70)\n",
            "\n",
            "    if len(df_window) == 0:\n",
            "        print(\"⚠️  분석 기간 내 데이터가 없습니다. TEMPORAL_WINDOW_DAYS를 늘려보세요.\")\n",
            "        continue\n",
            "\n",
            "    X_window = df_window[FEATURE_COLS].reset_index(drop=True)\n",
            "\n",
            "    sv_window_list = []\n",
            "    for model in models:\n",
            "        exp = shap.TreeExplainer(model)\n",
            "        sv_w = exp.shap_values(X_window)\n",
            "        if isinstance(sv_w, list):\n",
            "            sv_w = sv_w[1]\n",
            "        sv_window_list.append(sv_w)\n",
            "    mean_sv_window = np.mean(sv_window_list, axis=0)\n",
            "\n",
            "    max_pos_window = np.max(mean_sv_window, axis=0) \n",
            "    top_feat_idx = np.argsort(max_pos_window)[::-1][:top_n]\n",
            "    top_feat_names = [FEATURE_COLS[idx] for idx in top_feat_idx]\n",
            "\n",
            "    dates = df_window[fe_cfg.DATE_COL].dt.date.values\n",
            "    days_from_last = [- (ref_date.date() - d).days for d in dates]\n",
            "\n",
            "    fig, axes = plt.subplots(top_n + 1, 1, figsize=(12, 3 * (top_n + 1)), sharex=True)\n",
            "    fig.patch.set_facecolor('#ffffff')\n",
            "    \n",
            "    ax_prob = axes[0]\n",
            "    probs = df_window[\"_prob\"].values\n",
            "    \n",
            "    ax_prob.plot(days_from_last, probs, marker='o', color='#2c3e50', lw=2.5, markersize=5, label=\"Prediction Probability\")\n",
            "    ax_prob.axhline(BEST_T, color='#e74c3c', linestyle='--', lw=2, label=f\"Threshold (T={BEST_T:.3f})\")\n",
            "    ax_prob.fill_between(days_from_last, probs, BEST_T, where=(probs >= BEST_T), color='#e74c3c', alpha=0.15)\n",
            "    \n",
            "    if first_alarm_date is not None:\n",
            "        alarm_day = - (ref_date.date() - first_alarm_date.date()).days\n",
            "        if -window_days <= alarm_day <= 0:\n",
            "            ax_prob.axvline(alarm_day, color='#e74c3c', linestyle=':', lw=2.5, alpha=0.8)\n",
            "\n",
            "    ax_prob.set_ylabel(\"Probability\", fontsize=11, fontweight=\"bold\", color='#34495e')\n",
            "    ax_prob.set_title(\"Model Prediction Probability\", fontsize=13, fontweight=\"bold\", loc='left', color='#2c3e50')\n",
            "    ax_prob.set_ylim(-0.05, 1.05)\n",
            "    ax_prob.legend(loc='upper left', frameon=True, facecolor='white', edgecolor='#ecf0f1')\n",
            "    ax_prob.grid(axis='y', linestyle='--', alpha=0.4)\n",
            "    ax_prob.spines['top'].set_visible(False)\n",
            "    ax_prob.spines['right'].set_visible(False)\n",
            "    ax_prob.spines['left'].set_color('#bdc3c7')\n",
            "    ax_prob.spines['bottom'].set_color('#bdc3c7')\n",
            "\n",
            "    pos_color = '#e6614f'\n",
            "    neg_color = '#4a90e2'\n",
            "    \n",
            "    for ax, feat_name, feat_idx in zip(axes[1:], top_feat_names, top_feat_idx):\n",
            "        shap_vals = mean_sv_window[:, feat_idx]\n",
            "        bars = ax.bar(days_from_last, shap_vals, \n",
            "                      color=[pos_color if v > 0 else neg_color for v in shap_vals], \n",
            "                      alpha=0.85, width=0.8)\n",
            "        ax.axhline(0, color=\"#7f8c8d\", lw=1.2, ls=\"-\")\n",
            "        \n",
            "        if first_alarm_date is not None:\n",
            "            alarm_day = - (ref_date.date() - first_alarm_date.date()).days\n",
            "            if -window_days <= alarm_day <= 0:\n",
            "                ax.axvline(alarm_day, color='#e74c3c', linestyle=':', lw=2.5, alpha=0.5, zorder=0)\n",
            "\n",
            "        max_abs = max(abs(shap_vals.min()), abs(shap_vals.max())) * 1.1\n",
            "        if max_abs > 0:\n",
            "            ax.set_ylim(-max_abs, max_abs)\n",
            "            \n",
            "        ax.set_ylabel(\"SHAP Value\", fontsize=11, fontweight=\"bold\", color='#34495e')\n",
            "        ax.set_title(f\"Feature: {feat_name}\", fontsize=12, fontweight=\"bold\", loc='left', color='#2c3e50')\n",
            "        ax.grid(axis=\"y\", linestyle='--', alpha=0.4)\n",
            "        ax.spines['top'].set_visible(False)\n",
            "        ax.spines['right'].set_visible(False)\n",
            "        ax.spines['left'].set_color('#bdc3c7')\n",
            "        ax.spines['bottom'].set_color('#bdc3c7')\n",
            "\n",
            "    tick_locs = np.arange(-window_days + 1, 1, 5)\n",
            "    if 0 not in tick_locs:\n",
            "        tick_locs = np.append(tick_locs, 0)\n",
            "    \n",
            "    xticklabels = []\n",
            "    for x in tick_locs:\n",
            "        if x in days_from_last:\n",
            "            idx = days_from_last.index(x)\n",
            "            real_date = dates[idx].strftime('%m-%d')\n",
            "        else:\n",
            "            real_date = (ref_date + pd.Timedelta(days=int(x))).strftime('%m-%d')\n",
            "        xticklabels.append(f\"D{int(x)}\\n({real_date})\")\n",
            "\n",
            "    axes[-1].set_xticks(tick_locs)\n",
            "    axes[-1].set_xticklabels(xticklabels, fontsize=10, color='#34495e')\n",
            "    axes[-1].set_xlabel(f\"Timeline to {title_suffix}\", fontsize=12, fontweight=\"bold\", color='#2c3e50', labelpad=15)\n",
            "\n",
            "    fig.suptitle(\n",
            "        f\"Temporal SHAP Evolution & Risk Trajectory (Serial: {serial})\",\n",
            "        fontsize=16, fontweight=\"bold\", color='#2c3e50', y=1.02\n",
            "    )\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "    print(f\"\\n개체 {serial} 분석 완료. 상위 {top_n}개 피처: {top_feat_names}\")\n"
        ]
    }
]

for nb_file in ['notebooks/09b_true_positive_analysis.ipynb', 
                'notebooks/09c_normal_false_alarm_analysis.ipynb', 
                'notebooks/09d_early_alarm_analysis.ipynb', 
                'notebooks/09e_false_negative_analysis.ipynb']:
    with open(nb_file, 'r', encoding='utf-8') as f:
        nb = json.load(f)
        
    # Check if we already appended
    last_cell_src = "".join(nb['cells'][-1].get('source', []))
    if 'Temporal SHAP Evolution' not in last_cell_src:
        for cell in cells_to_append:
            # We must make a deep copy so we don't mutate the original dictionary
            import copy
            nb['cells'].append(copy.deepcopy(cell))
            
    with open(nb_file, 'w', encoding='utf-8') as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

print("Notebooks updated successfully!")
